# Generated by Django 4.1.2 on 2024-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='stock',
        ),
        migrations.AddField(
            model_name='auto',
            name='año',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.CharField(default='Default Model', max_length=100),
        ),
    ]
